### ISSUE TITLE
聚类如何实现的？

### ISSUE THREAD

**Issue by xiaohanghang** [funcwj/deep-clustering#1]
funcwj 您好：
  我有段代码不是很理解，希望您能帮忙解答下：
    def form_mask(classes, spkid, vad_mask):
            mask = ~vad_mask
            # mask = np.zeros_like(vad_mask)
            mask[vad_mask] = (classes == spkid)
            return mask
我想问题mask[vad_mask]这个举证可以再取矩阵吗

**Comment by funcwj** [comment]
mask[vad_mask] = (classes == spkid)
这行代码的意思是在非silence区域，如果聚类结果属于该说话人则设1，silence的bin上不做区分
