### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by fanmanqian** [funcwj/deep-clustering#12]
作者，您好，如果用TIMIT数据集，音频的混合以及.scp的生成有可以参考的资料吗？

**Comment by funcwj** [comment]
scp的生成自己写个脚本就行了，python或者shell，满足那样的格式就行。
数据混合你可以参考我的脚本产生 [here](https://github.com/funcwj/setk/tree/master/doc/data_simu)

**Comment by fanmanqian** [comment]
好的，非常感谢~


 
---原始邮件---
发件人: "Jian Wu"<notifications@github.com&gt;
发送时间: 2020年7月7日 19:28:43
收件人: "funcwj/deep-clustering"<deep-clustering@noreply.github.com&gt;;
抄送: "fanmanqian"<2563965485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [funcwj/deep-clustering] 数据集 (#12)




 
scp的生成自己写个脚本就行了，python或者shell，满足那样的格式就行。
 数据混合你可以参考我的脚本产生 here
