### ISSUE TITLE
训练数据集怎么准备？

### ISSUE THREAD

**Issue by aishoot** [funcwj/deep-clustering#2]
您好，非常感谢您的分享代码。有个问题想请教您，就是在Inference命令中“$mdl_dir”和“egs.scp”分别代表什么意思呢？还有就是在“train.yaml”文件中我没看到有关于test的数据地址？

**Comment by funcwj** [comment]
你好，"$mdl_dir"对应你训练的checkpoint目录，"egs.scp"是测试audio的.scp文件，每一行是一个"utt-id /path/to/mixed/utt"对。"train.yaml"里面只配置train和dev的数据地址用于训练，测试的时候在命令里面单独指示。

**Comment by aishoot** [comment]
好勒，感谢老铁
