### ISSUE TITLE
Have you implemented the deep attractor network?

### ISSUE THREAD

**Issue by aishoot** [funcwj/deep-clustering#4]
Hi, Wu Jian, have you implemented the Deep Attractor Network (DANet)?

**Comment by funcwj** [comment]
No, I haven't done it...

**Comment by aishoot** [comment]
OK, thanks

**Comment by njusq** [comment]
> Hi, Wu Jian, have you implemented the Deep Attractor Network (DANet)?

Hi, @pchao6! I am trying to implement DANet. If it is convenient for you, would you please help me? Thank you very much! My wechat: sqian960724
